
spring:
    application:
        name: mybatis-demo
    datasource:
        url: jdbc:mysql://localhost:3306/poetry?useSSL=false
#          url: jdbc:mysql://192.168.1.58:3306/edb_a20000?useSSL=false
        username: root
        password: 123456
server:
    port: 8081